call winget remove Microsoft.GetHelp_8wekyb3d8bbwe
call winget remove Microsoft.MixedReality.Portal_8wekyb3d8bbwe
call winget remove Microsoft.SkypeApp_kzf8qxf38zg5c
call winget remove Microsoft.WindowsFeedbackHub_8wekyb3d8bbwe
call winget remove Microsoft.YourPhone_8wekyb3d8bbwe
call winget remove Microsoft.ZuneVideo_8wekyb3d8bbwe
call winget remove Microsoft.549981C3F5F10_8wekyb3d8bbwe
call winget remove Microsoft.WindowsMaps_8wekyb3d8bbwe
call winget remove Microsoft.MicrosoftSolitaireCollection_8wekyb3d8bbwe
call winget remove Microsoft.Office.OneNote_8wekyb3d8bbwe
call winget remove Microsoft.Getstarted_8wekyb3d8bbwe
call winget remove Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe
call winget remove microsoft.windowscommunicationsapps_8wekyb3d8bbwe
call winget remove Disney.37853FC22B2CE_6rarf9sa4v8jt
call winget remove SpotifyAB.SpotifyMusic_zpdnekdrzrea0
@REM taskkill /f /im OneDrive.exe
call winget remove Microsoft.OneDrive
