#!/bin/bash
SERVICE="forgejo" 
FILE="repositories.txt"


if [[ "$SERVICE" == "forgejo" ]]; then
    echo Source -\> $SERVICE; echo

    while read REPOSITORY
    do
        AUTH_URL=$(echo "$REPOSITORY" | sed "s/https:\/\//https:\/\/${TOKEN}@/")
        echo
        git clone "$AUTH_URL"
    done < "$FILE"

fi

if [[ "$SERVICE" == "github" ]]; then
    echo Source -\> $SERVICE; echo

    gh auth status; echo
    while read REPOSITORY
    do
        gh repo clone "$RESPOSITORY"
        echo
    done < "$FILE"
fi


