#!/bin/bash
SERVICE="forgejo" 
TOKEN=""

if [[ "$SERVICE" == "forgejo" ]]; then
    echo SERVICE -\> $SERVICE; echo
    http https://git.dblocks.net/api/v1/user/repos?token=$TOKEN | jq -r '.[].name' | tee names.txt
    http https://git.dblocks.net/api/v1/user/repos?token=$TOKEN | jq -r '.[].html_url' | tee repositories.txt
fi

if [[ "$SERVICE" == "github" ]]; then
    echo SERVICE -\> $SERVICE; echo
    gh api --paginate /user/repos --jq '.[].html_url' | tee repositories.txt
    gh api --paginate /user/repos --jq '.[].name' | tee names.txt
fi
