#!/bin/bash
URLS="repositories.txt"
NAMES=names.txt

gh api --paginate /user/repos --jq '.[].html_url' | tee repositories.txt
gh api --paginate /user/repos --jq '.[].name' | tee names.txt

echo; gh auth status; echo
while read -r REPOSITORY
do
    gh repo clone "$REPOSITORY"
    echo
done < "$URLS"

echo; gh auth status; echo
while read -r REPOSITORY 
do
    echo "$(pwd)/$REPOSITORY"
    git -C "$REPOSITORY" pull
    echo    
done < "$NAMES"


for vol in $(docker volume ls -q); do mkdir -p "./$vol" && docker run --rm -v "$vol":/data alpine tar -c -C /data . | tar -x -C "./$vol"; done
# for dir in */; do vol="${dir%/}"; docker volume create "$vol" && tar -c -C "$dir" . | docker run --rm -i -v "$vol":/data alpine tar -x -C /data; done
# cp $HOME/.var/usebottles

