#!/bin/bash
# SERVICE="forgejo" 
SERVICE="github" 

if [[ "$SERVICE" == "forgejo" ]]; then
    echo Source -\> $SERVICE; echo
fi

if [[ "$SERVICE" == "github" ]]; then
    echo Source -\> $SERVICE; echo

    FILE=repositories.txt

    gh auth status; echo

    for RESPOSITORY in `cat $FILE`
    do
        gh repo clone $RESPOSITORY
        echo
    done
fi


