#!/bin/bash
SOURCE="github" 
# SOURCE="forgejo" 

if [[ "$SOURCE" == "forgejo" ]]; then
    echo Source -\> $SOURCE; echo 

fi

if [[ "$SOURCE" == "github" ]]; then
    echo Source -\> $SOURCE; echo 

    ROOT=/media
    USER=user1
    DRIVE=CORSAIR
    FILE=names.txt

    gh auth status
    echo

    for RESPOSITORY in `cat $FILE`
    do
    cd $ROOT/$USER/$DRIVE/$RESPOSITORY && pwd && git pull
    echo    
    done
fi
